server {
    # Listen only on HTTPS (Inception rule)
    listen 443 ssl;
    listen [::]:443 ssl;

    # domain name (Must be your intra login)
    server_name asyani.42.fr;

    # SSL Configuration (Strictly TLS 1.2 and 1.3)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Where the website files live
    root /var/www/html/wordpress;
    index index.php index.html index.htm;

    # Route standard requests (Check if file exists, else 404 error)
    location / {
        try_files $uri $uri/ =404;
    }

    # Route PHP requests to the WordPress container
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # This is the magic line that links the containers:
        fastcgi_pass wordpress:9000;
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
