services:
  # MARIADB database service
  mariadb:
    build:
      context: ./requirements/mariadb 
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net
  
  wordpress:
    # WORDPRESS (PHP-FPM) service
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception_net

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception_net

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
        - inception_net

  ftp_server:
    build:
      context: ./requirements/bonus/ftp_server
      dockerfile: Dockerfile
    container_name: ftp_server
    restart: always
    depends_on:
      - wordpress
    networks:
        - inception_net

  static_website:
    build:
      context: ./requirements/bonus/static_website
      dockerfile: Dockerfile
    container_name: static_website
    restart: always
    networks:
        - inception_net

volumes:
    db_data:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/abdellah/data/mariadb
    wp_data:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/abdellah/data/wordpress

networks:
    inception_net:
      driver: bridge
