# Run in the foreground so Docker doesn't crash
listen=YES
listen_ipv6=NO

# Security: No anonymous logins, only real users
anonymous_enable=NO
local_enable=YES
write_enable=YES

# Lock the user inside their home folder (/var/www/html)
chroot_local_user=YES
allow_writeable_chroot=YES

# Local user root folder
local_root=/var/www/html/wordpress

# change the permission to read any file uploaded from ftp
local_umask=022

# PASSIVE MODE CONFIGURATION (Crucial for Docker NAT)
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# Allow vsftpd to run smoothly in modern Linux environments
seccomp_sandbox=NO
